sudo: required
services:
  - docker
env: 
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 # Cloud CLI dont display any prompts that require user input
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null; # install sdk & install locally to travis instance
  - source $HOME/google-cloud-sdk/path.bash.inc # Shell modification
  - gcloud components update kubectl # Install Kubectl
  - gcloud components auth activate-service-account --key-file service-account.json # Auth
